BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CoverTypeController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CoverTypeController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        IEnumerable<CoverType> objCoverTypes = _unitOfWork.CoverType.GetAll();
        return View(objCoverTypes);
    }

    //GET - Create
    public IActionResult Create()
    {
        return View();
    }

    //POST - Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CoverType obj)
    {
        if(obj.Name == string.Empty)
        {
            ModelState.AddModelError("emptyName", "The name cannot be empty.");
        }
        if(ModelState.IsValid)
        {
            _unitOfWork.CoverType.Add(obj);
            _unitOfWork.Save();
            TempData["success"] = "Cover type created successfully!";
            return RedirectToAction("Index");
        }
        return View();
    }

    //GET - Edit
    public IActionResult Edit(int? id)
    {
        if (id == null || id ==0 )
        {
            return NotFound();
        }

        var CoverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u=>u.Id == id);

        if(CoverTypeFromDbFirst == null)
        {
            return NotFound();
        }

        return View(CoverTypeFromDbFirst);
    }

    //POST - Edit
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit (CoverType obj)
    {
        if(obj.Id == null || obj.Name == string.Empty)
        {
            ModelState.AddModelError("emptyFields", "The fields cannot be empty.");
        }

        if(ModelState.IsValid)
        {
            _unitOfWork.CoverType.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "Cover type edited successfully!";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    //GET - Remove
    public IActionResult Remove (int? id)
    {
        if(id == null || id == 0 )
        {
            return NotFound();
        }

        var coverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

        if(coverTypeFromDbFirst == null)
        {
            return NotFound();
        }

        return View(coverTypeFromDbFirst);
    }

    //POST - Remove
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Remove (CoverType obj)
    {
        _unitOfWork.CoverType.Remove(obj);
        _unitOfWork.Save();
        TempData["success"] = "Cover type removed successfully!";
        return RedirectToAction("Index");
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-s">
            <h2 class="text-primary">Create Cover Type</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-s">
            <h2 class="text-primary">Edit Cover Type</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Cover Type List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Cover Type
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Cover Type Name
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="80%">
                        @item.Name
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="CoverType" asp-action="Remove" asp-route-id="@item.Id" class="btn btn-danger mx-2"><i class="bi bi-x-circle"></i> Remove</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BulkyBookWeb/Areas/Admin/Views/CoverType/Remove.cshtml
@model CoverType

<form method="post" asp-action="Remove">
    <div class="border p-3 mt-4">
        <div class="row pb-s">
            <h2 class="text-primary">Remove Cover Type</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Id"></label>
            <input asp-for="Id" class="form-control" readonly/>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" readonly />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Remove</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }